name: "Hello world"
description: "Add-on for crawling commuting times"
version: "0.0.61"
slug: "hello_world"
init: false
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
  8001/tcp: 8001
  8002/tcp: 8002
options:
  test: 5
schema:
  test: int