name: "Hello world"
description: "My first real add-on!"
version: "0.0.35"
slug: "hello_world"
init: false
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
options:
  test: 5
schema:
  test: int
