name: "Hello world"
description: "Add-on for crawling commuting times"
version: "0.0.72"
slug: "hello_world"
init: false
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
options:
  traffic_provider:
    - Google Maps
    - TomTom
    - WAZE
schema:
  traffic_provider:
    - list(Google Maps|TomTom|WAZE)